# This is a basic workflow to help you get started with Actions

name: Benchmark
env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
permissions:
      id-token: write 
      contents: read 
      pull-requests: write 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_run:
    workflows: ["Terraform action"]
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  cassandra-setup:
    runs-on: ubuntu-latest
    env:
      SCALLA_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_SCALLA }}
      
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Use scalla_key
        run: |
          echo "$SCALLA_PRIVATE_KEY" > scalla-key.pem
          chmod 400 scalla-key.pem
        working-directory: ./scripts/cassandra
          
      - name: Cassandra Setup
        run: bash cassandra-setup.sh
        working-directory: ./scripts/cassandra

  scylla-setup:
    env:
      SCALLA_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_SCALLA }}
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Use scalla_key
        run: |
          echo "$SCALLA_PRIVATE_KEY" > scalla-key.pem
          chmod 400 scalla-key.pem
          cat scalla-key.pem
        working-directory: ./scripts/scylla

      - name: Scylla Setup
        run: bash scylla-setup.sh
        working-directory: ./scripts/scylla

  ycsb-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Use scalla_key
        run: |
          echo "$SCALLA_PRIVATE_KEY" > scalla-key.pem
          chmod 400 scalla-key.pem
        working-directory: ./scripts

      - name: Loading and Runnning ycsb benchmark
        run: bash ycsb.sh
        working-directory: ./scripts
    needs: [cassandra-setup, scylla-setup ]

  move-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Use scalla_key
        run: |
          echo "$SCALLA_PRIVATE_KEY" > scalla-key.pem
          chmod 400 scalla-key.pem
        working-directory: ./scripts

      - name: Transfering results to s3 bucket
        run: bash copy-to-s3.sh
        working-directory: ./scripts
    needs: ycsb-benchmark

  clean-up-scylla:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Use scalla_key
        run: |
          echo "$SCALLA_PRIVATE_KEY" > scalla-key.pem
          chmod 400 scalla-key.pem
        working-directory: ./scripts/scylla

      - name: cleaning systems before the next run
        run: bash cleanup.sh
        working-directory: ./scripts/scylla
    needs: move-to-s3

  clean-up-cassandra:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Use scalla_key
        run: |
          echo "$SCALLA_PRIVATE_KEY" > scalla-key.pem
          chmod 400 scalla-key.pem
        working-directory: ./scripts/cassandra

      - name: cleaning systems before the next run
        run: bash cleanup.sh
        working-directory: ./scripts/cassandra
    needs: move-to-s3
